/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

import java.sql.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author nashiaholloway
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    public Employee() {
        initComponents();
        selection();
        
    }
    
    public void selection(){
        try{
        conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CuvinoRestaurant", "user123", "123");
        st = conn.createStatement();
        rs = st.executeQuery("Select * from user123.employee");     //data from Employee Database querie will show up in EmployeeTable GUI
        
        EmployeeTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        } catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        SSNTxt = new javax.swing.JTextField();
        Pay_RateTxt = new javax.swing.JTextField();
        FNameTxt = new javax.swing.JTextField();
        SuperSSNTxt = new javax.swing.JTextField();
        Mid_InitTxt = new javax.swing.JTextField();
        DNOTxt = new javax.swing.JTextField();
        LNameTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        Hours_WorkedTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "FName", "Mid_Init", "LName", "Hours_Worked", "Pay_Rate", "SuperSSN", "DNO", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        EmployeeTable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(EmployeeTable);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        FNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameTxtActionPerformed(evt);
            }
        });

        Mid_InitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mid_InitTxtActionPerformed(evt);
            }
        });

        DNOTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNOTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("SSN");

        jLabel2.setText("FName");

        jLabel3.setText("Mid_Init");

        jLabel4.setText("LName");

        jLabel5.setText("Hours_Worked");

        jLabel6.setText("Pay_Rate");

        jLabel7.setText("SuperSSN");

        jLabel8.setText("DNO");

        jLabel9.setText("Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(addBtn)
                                .addGap(113, 113, 113)
                                .addComponent(deleteBtn)
                                .addGap(99, 99, 99)
                                .addComponent(updateBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(SSNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(Pay_RateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(FNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Mid_InitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(SuperSSNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(Hours_WorkedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn)
                    .addComponent(updateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mid_InitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hours_WorkedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pay_RateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DNOTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SuperSSNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mid_InitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mid_InitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Mid_InitTxtActionPerformed

    private void FNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameTxtActionPerformed

    private void DNOTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNOTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNOTxtActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Delete from user123.employee where SSN =" + SSNTxt.getText();
            Statement delete = conn.createStatement();
            delete.executeUpdate(sql);
            SSNTxt.setText("");
            FNameTxt.setText("");
            Mid_InitTxt.setText("");
            LNameTxt.setText("");
            Hours_WorkedTxt.setText("");
            Pay_RateTxt.setText("");
            SuperSSNTxt.setText("");
            DNOTxt.setText("");
            AddressTxt.setText("");
            
        }catch (SQLException e){
            e.printStackTrace();
        }
        selection(); //prints table again after delete
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        /*
        try{
            String sql = "Update user123.employee set SSN = '"+ SSNTxt.getText()+"'"+", FName = '"+FNameTxt.getText()+"'"+
                    ", Mid_Init = '"+ Mid_InitTxt.getText()+"'"+", LName = '"+ LNameTxt.getText()+"'"+
                    ", Hours_Worked = '"+ Hours_WorkedTxt.getText()+"'"+", Pay_Rate = '"+ Pay_RateTxt.getText()+"'"+
                    ", Address = '"+ AddressTxt.getText()+"'"+", SuperSSN = '"+ SuperSSNTxt.getText()+"'"+
                    ", DNO = '"+ DNOTxt.getText();
            Statement update = conn.createStatement();
            update.executeUpdate(sql);
        }catch (SQLException e){
            e.printStackTrace();
        }
        selection(); //prints table again after update
        */
        try{
            String SSN = SSNTxt.getText();
            String FName = FNameTxt.getText();
            String Mid_Init = Mid_InitTxt.getText();
            String LName = LNameTxt.getText();
            Double Hours_Worked = Double.parseDouble(Hours_WorkedTxt.getText());
            Double Pay_Rate = Double.parseDouble(Pay_RateTxt.getText());
            String Address = AddressTxt.getText();
            String SuperSSN = SuperSSNTxt.getText();
            int DNO = Integer.parseInt(DNOTxt.getText());
            
            String sql = "UPDATE user123.employee SET WHERE SSN=? (?, ?, ?, ?, ?, ?, ?, ?)";
        
            PreparedStatement add = conn.prepareStatement(sql);
            add.setString(1, SSN);
            add.setString(2, FName);
            add.setString(3, Mid_Init);
            add.setString(4, LName);
            add.setDouble(5, Hours_Worked);
            add.setDouble(6, Pay_Rate);
            add.setString(7, Address);
            add.setString(8, SuperSSN);
            add.setInt(9, DNO);
            
        
            add.executeUpdate(); //update table after updating user
        } catch(SQLException e){
            e.printStackTrace();
        }
        selection();   //print table after update
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try{
            String SSN = SSNTxt.getText();
            String FName = FNameTxt.getText();
            String Mid_Init = Mid_InitTxt.getText();
            String LName = LNameTxt.getText();
            Double Hours_Worked = Double.parseDouble(Hours_WorkedTxt.getText());
            Double Pay_Rate = Double.parseDouble(Pay_RateTxt.getText());
            String Address = AddressTxt.getText();
            String SuperSSN = SuperSSNTxt.getText();
            int DNO = Integer.parseInt(DNOTxt.getText());
            
            String sql = "INSERT INTO user123.employee VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
            PreparedStatement add = conn.prepareStatement(sql);
            add.setString(1, SSN);
            add.setString(2, FName);
            add.setString(3, Mid_Init);
            add.setString(4, LName);
            add.setDouble(5, Hours_Worked);
            add.setDouble(6, Pay_Rate);
            add.setString(7, Address);
            add.setString(8, SuperSSN);
            add.setInt(9, DNO);
        
            add.executeUpdate(); //update table after adding new user
        } catch(SQLException e){
            e.printStackTrace();
        }
        selection();   //print table after update       
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField DNOTxt;
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JTextField FNameTxt;
    private javax.swing.JTextField Hours_WorkedTxt;
    private javax.swing.JTextField LNameTxt;
    private javax.swing.JTextField Mid_InitTxt;
    private javax.swing.JTextField Pay_RateTxt;
    private javax.swing.JTextField SSNTxt;
    private javax.swing.JTextField SuperSSNTxt;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
